spring:
  application:
    name: employee-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    username: root
    password: admin
    url: jdbc:mysql://localhost:3306/project

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0

server:
  port: 8081

jwt:
  secret:
    key: "404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970"