spring:
  application:
    name: gateway-service
  config:
    import: "optional:configserver:http://localhost:8088"
  cloud:
    gateway:
      routes:
        - id: employee-service
          uri: lb://employee-service
          predicates:
            - Path=/employee/**
        - id: idp-service
          uri: lb://idp-service
          predicates:
            - Path=/identity/**
        - id: employee-leave
          uri: lb://employee-leave
          predicates:
            - Path=/leave/**
