spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    password: password
    url: jdbc:mysql://localhost:3306/project
    username: root

server:
  port: 8085

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret:
    key: "404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970"

management:
  tracing:
    sampling:
      probability: 1.0